- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2023061218033700060000000c.crlnswkkjx3m.us-east-1.rds.amazonaws.com"
    login_user: "victor"
    login_password: "devopspblproject"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2023061218033700060000000c.crlnswkkjx3m.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "victor" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "devopspblproject" }


